name: mss

services:
  db:
    image: mariadb:11.8
    container_name: mss-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PWD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_USER_PWD}
    ports:
      - "3306:3306"
    networks:
      - mss-network
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  adminer:
    image: adminer:5.4.2
    container_name: mss-adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: ${DB_HOST}
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - mss-network

  api:
    build: ./api
    image: jublaaarau/mss-api:latest
    container_name: mss-api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - mss-network
    volumes:
      - ./api:/app
      - /app/node_modules
    
      

networks:
  mss-network:
    driver: bridge

volumes:
  db_data: